apiVersion: v1
kind: Service
metadata:
  name: student-portal-nodeport
spec:
  type: NodePort
  selector:
    app: student-portal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080   # optional; if omitted, Kubernetes picks a port in 30000-32767
